## logistic

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas.plotting import scatter_matrix
%matplotlib inline

In [4]:
df = pd.read_csv("logis_part2.csv")
df.head()

Mining and quarrying  Accommodation and food service activities  \
0           1206.373717                                3499.423513   
1           6211.990349                                1402.792162   
2           1084.257727                                 620.611510   
3            177.441005                                 261.883467   
4            135.829909                                 249.025557   

   Administrative and support service activities  accuracy  
0                                            623         0  
1                                            796         1  
2                                            108         1  
3                                            149         1  
4                                             57         0

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [7]:
df.columns

Index(['Mining and quarrying', 'Accommodation and food service activities',
       'Administrative and support service activities', 'accuracy'],
      dtype='object')

In [10]:
import statsmodels.api as sm
X = df[['Mining and quarrying', 'Accommodation and food service activities',
       'Administrative and support service activities']]
X = sm.add_constant(X, prepend=False)
X.head()

Mining and quarrying  Accommodation and food service activities  \
0           1206.373717                                3499.423513   
1           6211.990349                                1402.792162   
2           1084.257727                                 620.611510   
3            177.441005                                 261.883467   
4            135.829909                                 249.025557   

   Administrative and support service activities  const  
0                                            623    1.0  
1                                            796    1.0  
2                                            108    1.0  
3                                            149    1.0  
4                                             57    1.0

In [11]:
y = df['accuracy']

In [12]:
# lecture example uses all data to train (test_size=0.0).
# typically, test_size is set to be 0.30

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=99)

In [13]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [14]:
model.coef_

array([[-6.34994605e-05,  4.21089057e-05,  2.58218049e-05,
         6.06844034e-01]])

In [15]:
model.intercept_

array([0.6068443])

In [16]:
# lecture example uses all data to train
# typically use X_test to do prediction

predictions = model.predict(X_train)
predictions

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [17]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(confusion_matrix(y_train,predictions))

[[ 0 12]
 [ 1 40]]


In [18]:
# lecture example uses all data to train
# typically use y_test to observe confusion matrix 

print(classification_report(y_train, predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        12
           1       0.77      0.98      0.86        41

    accuracy                           0.75        53
   macro avg       0.38      0.49      0.43        53
weighted avg       0.60      0.75      0.67        53



In [19]:
#2012
y = (np.exp(0.6068443+(-6.34994605e-05*1209)+(4.21089057e-05*2317)+(2.58218049e-05*2302)))/(1+(np.exp(0.6068443+(-6.34994605e-05*1209)+(4.21089057e-05*2317)+(2.58218049e-05*2302))))
y

0.6653173959103209

In [20]:
#2014
y = (np.exp(0.6068443+(-6.34994605e-05*1334)+(4.21089057e-05*2370)+(2.58218049e-05*2687)))/(1+(np.exp(0.6068443+(-6.34994605e-05*1334)+(4.21089057e-05*2370)+(2.58218049e-05*2687))))
y

0.666259906151468

In [21]:
#2016
y = (np.exp(0.6068443+(-6.34994605e-05*2261)+(4.21089057e-05*2648)+(2.58218049e-05*2610)))/(1+(np.exp(0.6068443+(-6.34994605e-05*2261)+(4.21089057e-05*2648)+(2.58218049e-05*2610))))
y

0.6552441237880016